# Generated by Django 5.0.7 on 2024-07-31 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Organiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('link_to_pfp', models.CharField(max_length=2000)),
                ('link_to_cover_image', models.CharField(max_length=2000)),
                ('events_organised', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account_creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('link_to_pfp', models.CharField(max_length=2000)),
                ('link_to_cover_image', models.CharField(max_length=2000)),
                ('number_of_times_volunteered', models.DecimalField(decimal_places=2, max_digits=4)),
                ('hours_of_volunteering', models.FloatField()),
                ('account_creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('place', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1000)),
                ('link_to_pfp', models.CharField(max_length=2000)),
                ('link_to_cover_image', models.CharField(max_length=2000)),
                ('number_of_volunteers', models.DecimalField(decimal_places=2, max_digits=4)),
                ('edition', models.DecimalField(decimal_places=2, max_digits=4)),
                ('organisers', models.ManyToManyField(to='volunteering.organiser')),
                ('volunteers', models.ManyToManyField(to='volunteering.volunteer')),
            ],
        ),
    ]
