# Generated by Django 5.1.1 on 2025-01-01 09:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='callout',
            name='organiser',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='volunteering.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='account_creation_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
        ),
    ]
