# Generated by Django 5.0.7 on 2024-08-02 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='experience',
            name='location',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='experience',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='edition',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_to_cover_image',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='link_to_pfp',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_volunteers',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='organisers',
            field=models.ManyToManyField(blank=True, to='volunteering.organiser'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='volunteers',
            field=models.ManyToManyField(blank=True, to='volunteering.volunteer'),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='account_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='events_organised',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='link_to_cover_image',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='organiser',
            name='link_to_pfp',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='account_creation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='hours_of_volunteering',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='link_to_cover_image',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='link_to_pfp',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='number_of_times_volunteered',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
        ),
    ]
