# Generated by Django 5.1.1 on 2025-01-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_callout_organiser_alter_user_account_creation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callout',
            old_name='organiser',
            new_name='sender',
        ),
    ]
