# Generated by Django 5.0.7 on 2024-08-04 20:39

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0002_remove_event_place_event_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='account_creation_date',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='account_creation_date',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2024, 8, 4)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteering.organiser')),
            ],
        ),
    ]
