# Generated by Django 5.1.1 on 2025-01-24 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0003_alter_useraddedparticipation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 1, 24)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 1, 24)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 24)),
        ),
    ]
