# Generated by Django 5.1.1 on 2025-01-28 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0004_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 28)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 28)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 28)),
        ),
    ]
