# Generated by Django 5.1.1 on 2025-01-29 09:37

import datetime
import volunteering.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0005_alter_useraddedparticipation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 29)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='location',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 29)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 29)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_uaimg.png', null=True, upload_to=volunteering.models.upload_to),
        ),
    ]
