# Generated by Django 5.1.1 on 2025-01-29 09:40

import volunteering.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0006_alter_useraddedparticipation_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='participation_picture',
            field=models.ImageField(blank=True, default='images/default_uaimg.png', upload_to=volunteering.models.upload_to),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=volunteering.models.upload_to),
        ),
    ]
