# Generated by Django 5.1.1 on 2025-01-31 07:33

import datetime
import volunteering.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0007_alter_useraddedparticipation_participation_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddedparticipation',
            name='hours',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 31)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 1, 31)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 1, 31)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_pfp.png', null=True, upload_to=volunteering.models.upload_to),
        ),
    ]
