# Generated by Django 5.1.1 on 2025-02-03 21:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0008_useraddedparticipation_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callout',
            name='opportunity',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='volunteering.opportunity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='end_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 3)),
        ),
        migrations.AlterField(
            model_name='useraddedparticipation',
            name='start_date',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 3)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2025, 2, 3)),
        ),
    ]
