# Generated by Django 5.1.1 on 2025-02-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0009_callout_opportunity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callout',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
