# Generated by Django 5.1.1 on 2025-02-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteering', '0011_alter_callout_opportunity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callout',
            name='time',
        ),
        migrations.AddField(
            model_name='usertocallout',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
